FROM alpine:3.14.2

# update system and install redis
RUN apk --update add redis

# ADD 'run.sh' and make it executeable
ADD     ./tools/redis.sh /
RUN     chmod +x /redis.sh

# start redis cache
ENTRYPOINT [ "./redis.sh" ]